completed ticket 11
dmarkesini/Backend-project pull request #10
Opened 2022-08-04 14:50 UTC by dmarkesini

-used TDD
-error handled if the query topic does not exist in databse

2022-08-04 15:14 UTC, HeatherEver reviewed
Lovely! Just a couple of tests to add in which case you might want to add a valid sort_by and valid order_by comparison so people can't add dodgy things into a query

2022-08-04 15:14 UTC, HeatherEver commented on __tests__/app.test.js
> +  });
can you please add some tests for invalid sort_by and invalid order

2022-08-04 15:14 UTC, HeatherEver commented on __tests__/app.test.js
> +const { expect } = require("@jest/globals");
weird jest auto import - just remove this line in case it causes any issues

2022-08-04 15:42 UTC, Rosem10 requested changes
Just one more test to add please!

2022-08-04 15:42 UTC, Rosem10 commented on __tests__/app.test.js
> +  });
What if the topic exists but there are no associated artickes?

2022-08-04 15:42 UTC, Rosem10 commented on models/articles.models.js
> +        `SELECT articles.article_id, articles.author, articles.title, articles.topic, articles.created_at, articles.votes,
This works and is fine - but you could make it waaaay DRY-er by having one 'base' query string saved as a variable, and concatenating the values you want (e.g topic) to it, depending on whether there is one or not. At the moment there is a lot of crossover between the two db.queries.

2022-08-05 08:04 UTC, HeatherEver approved these changes

2022-08-05 08:21 UTC, merged